let currentItinerary = null;
let selectedRating = 5;
let currentReplanDay = null;

const DAY_ICON = { Morning: "🌅", Afternoon: "🍛", Evening: "🌄" };

function renderStars() {
  const wrap = document.getElementById("starRating");
  wrap.innerHTML = [1, 2, 3, 4, 5].map((n) => `
    <span class="star-pick" data-val="${n}" style="cursor:pointer; font-size:1.6rem; color:${n <= selectedRating ? '#FFD166' : 'rgba(255,255,255,0.15)'};">★</span>
  `).join("");
  wrap.querySelectorAll(".star-pick").forEach((el) => {
    el.addEventListener("click", () => {
      selectedRating = parseInt(el.dataset.val, 10);
      renderStars();
    });
  });
}

function renderTimeline() {
  const container = document.getElementById("timelineContainer");
  const itn = currentItinerary;

  container.innerHTML = itn.itinerary.map((day, idx) => `
    <div class="glass p-4 mb-4 fade-up delay-${Math.min(idx, 3)}">
      <div class="d-flex justify-content-between align-items-center mb-3">
        <h4 class="fw-semibold mb-0">Day ${day.day}</h4>
        <span class="text-mist small">Est. ${currency(day.estimated_cost)}</span>
      </div>
      <div class="timeline">
        ${["morning", "afternoon", "evening"].map((slot) => `
          <div class="timeline-item">
            <div class="timeline-dot">${DAY_ICON[slot.charAt(0).toUpperCase() + slot.slice(1)]}</div>
            <div class="d-flex justify-content-between align-items-start">
              <div>
                <div class="text-mist small text-uppercase" style="letter-spacing:.05em;">${slot}</div>
                <div class="fw-medium">${day[slot]}</div>
              </div>
              <button class="btn btn-tm-ghost btn-sm replan-day-btn" data-day="${day.day}">🔄 Change</button>
            </div>
          </div>
        `).join("")}
      </div>
    </div>
  `).join("");

  container.querySelectorAll(".replan-day-btn").forEach((btn) => {
    btn.addEventListener("click", () => openReplanModal(parseInt(btn.dataset.day, 10)));
  });
}

function renderSummary() {
  const itn = currentItinerary;
  document.getElementById("itnTitle").textContent = `${itn.days}-day journey to ${itn.destination}`;
  document.getElementById("itnSubtitle").textContent =
    `${itn.travelers} traveler(s) · Generated by ${itn.generator === "llm" ? "AI (LLM)" : "TripMind's itinerary engine"}`;

  document.getElementById("sumMatch").textContent = itn.match_score != null ? `${itn.match_score}%` : "—";
  document.getElementById("sumBudget").textContent = currency(itn.budget);
  document.getElementById("sumCost").textContent = currency(itn.estimated_cost);

  const remaining = itn.remaining_budget;
  const remainingEl = document.getElementById("sumRemaining");
  remainingEl.textContent = currency(remaining);
  remainingEl.className = remaining >= 0 ? "text-mint" : "text-sunset";

  const pct = Math.min(100, Math.round((itn.estimated_cost / itn.budget) * 100));
  document.getElementById("sumProgress").style.width = `${pct}%`;
}

function openReplanModal(dayNumber) {
  currentReplanDay = dayNumber;
  document.getElementById("replanDayLabel").textContent = `Day ${dayNumber}`;
  const day = currentItinerary.itinerary.find((d) => d.day === dayNumber);
  const select = document.getElementById("replanActivitySelect");
  select.innerHTML = ["morning", "afternoon", "evening"]
    .map((slot) => `<option value="${day[slot]}">${slot.charAt(0).toUpperCase() + slot.slice(1)}: ${day[slot]}</option>`)
    .join("");
  document.getElementById("replanAlert").innerHTML = "";
  new bootstrap.Modal(document.getElementById("replanModal")).show();
}

async function confirmReplan() {
  const btn = document.getElementById("confirmReplanBtn");
  const alertBox = document.getElementById("replanAlert");
  setButtonLoading(btn, true, "Rebuilding");
  try {
    const avoid = document.getElementById("replanActivitySelect").value;
    const data = await apiRequest("/itinerary/replan-day", {
      method: "POST",
      body: { itinerary_id: currentItinerary.itinerary_id, day: currentReplanDay, avoid_activity: avoid },
    });

    currentItinerary.itinerary = currentItinerary.itinerary
      .filter((d) => d.day !== currentReplanDay)
      .concat([data.updated_day])
      .sort((a, b) => a.day - b.day);
    currentItinerary.estimated_cost = data.estimated_cost;
    currentItinerary.remaining_budget = currentItinerary.budget - data.estimated_cost;

    sessionStorage.setItem("tm_itinerary", JSON.stringify(currentItinerary));
    renderTimeline();
    renderSummary();
    bootstrap.Modal.getInstance(document.getElementById("replanModal")).hide();
  } catch (err) {
    showAlert(alertBox, err.message);
  } finally {
    setButtonLoading(btn, false);
  }
}

async function submitFeedback() {
  const btn = document.getElementById("submitFeedbackBtn");
  const alertBox = document.getElementById("feedbackAlert");
  const userId = Auth.userId();

  if (!userId) {
    showAlert(alertBox, `Please <a href="index.html#auth">log in</a> to save feedback.`, "warning");
    return;
  }

  setButtonLoading(btn, true, "Saving");
  try {
    await apiRequest("/feedback", {
      method: "POST",
      body: {
        user_id: userId,
        destination: currentItinerary.destination,
        rating: selectedRating,
        liked: [],
        disliked: [],
        feedback: "",
      },
    });
    showAlert(alertBox, "Thanks! We'll use this for future recommendations.", "success");
  } catch (err) {
    showAlert(alertBox, err.message);
  } finally {
    setButtonLoading(btn, false);
  }
}

document.addEventListener("DOMContentLoaded", () => {
  const raw = sessionStorage.getItem("tm_itinerary");
  if (!raw) {
    showAlert(document.getElementById("itnAlert"),
      `No itinerary found yet. <a href="planner.html">Plan a trip first</a>.`, "warning");
    return;
  }
  currentItinerary = JSON.parse(raw);
  renderSummary();
  renderTimeline();
  renderStars();

  document.getElementById("confirmReplanBtn").addEventListener("click", confirmReplan);
  document.getElementById("submitFeedbackBtn").addEventListener("click", submitFeedback);
});
